version: '3'

services:
  mysql-springdb:
    image: mysql:8.0.29-debian
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser@123

  springboot-docker-container:
    image: springboot-docker-container
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-springdb
  react-docker-container:
    image: react-docker-container
    build:
      context: front-end/
      dockerfile: Dockerfile
    depends_on:
      - springboot-docker-container