version: '3'

services:
  mysql-springdb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser@123

  springboot-docker-container:
    image:springboot-docker-container
    port:
      -8080:8080
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-springdb
  react-docker-container:
    image: react-docker-container
    port:
      -3000:3000
    build:
      context: front-end/
      dockerfile: Dockerfile
    depends_on:
      - springboot-docker-container